server:
  port: 8082

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes[0].id: bookCheckHealth
      routes[0].uri: lb://bclient
      routes[0].predicates[0]: Path=/checkBookHealth
      routes[0].predicates[1]: Method=GET
      routes[1].id: orderCheckHealth
      routes[1].uri: lb://oclient
      routes[1].predicates[0]: Path=/checkOrderHealth
      routes[1].predicates[1]: Method=GET
      routes[2].id: userCheckHealth
      routes[2].uri: lb://uclient
      routes[2].predicates[0]: Path=/checkUserHealth
      routes[2].predicates[1]: Method=GET
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"


