server:
  port: 0

spring:
  application:
    name: BookServer
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book-service
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka

logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"
