server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  cloud:
    compatibility-verifier:
      enabled: true
  application:
    name: book-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/book-service
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor: TRACE



#
#logging:
#  com:
#    netflix:
#      discovery: DEBUG
#  pattern:
#    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"
